services:
  api1: &api
    depends_on:
      - redis
    #image: weversonlemos/cepsearch:latest
    build: .
    container_name: api1
    restart: always
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      PORT: 8080
    networks:
      - cs-be
    deploy:
      resources:
        limits:
          memory: 512M

  api2:
    <<: *api
    container_name: api2
    ports:
      - "8081:8081"
    environment:
      REDIS_HOST: redis
      PORT: 8081

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cs-be
    deploy:
      resources:
        limits:
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - cs-be
    deploy:
      resources:
        limits:
          memory: 256M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    networks:
      - cs-be
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    deploy:
      resources:
        limits:
          memory: 256M

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - cs-be
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  cs-be:
    driver: bridge

volumes:
  grafana-data:
