version: "3.9"

services:
  cepsearch-api:
    depends_on:
      - cepsearch-cache
    image: weversonlemos/cepsearch:latest
    container_name: cepsearch-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      HOST: cepsearch-cache
    networks:
      - cs-be

  cepsearch-cache:
    image: redis:latest
    container_name: cepsearch-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cs-be

networks:
  cs-be:
    driver: bridge
