FROM maven:3.6.3-jdk-8-slim AS build
COPY src /app/src
COPY pom.xml /app/pom.xml
WORKDIR /app
RUN mvn package

FROM openjdk:8-jre-slim-buster
EXPOSE 8080
COPY --from=build /app/target/app.jar /app/app.jar
WORKDIR /app
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dlog4j2.formatMsgNoLookups=true", "-jar", "./app.jar"]
