openapi: 3.0.1
info:
  title: Address search by postal code
  description: This microservice is responsible for consuming an external API and
    getting addresses by postal code
  contact:
    name: Weverson Lemos
    url: https://github.com/WeversonL/cepsearch
    email: weversonl@proton.me
  version: 1.1.0
  x-technical-owner: Weverson Lemos
servers:
  - url: http://localhost:8080/api/cep
tags:
  - name: Address search by postal code
    description: This microservice is responsible for consuming an external API and
      getting addresses by postal code
paths:
  /{cep}:
    get:
      tags:
        - Address search by postal code
      summary: getting addresses
      description: This microservice is responsible for consuming an external API
        and getting addresses by postal code
      operationId: cepsearchGet
      parameters:
        - name: cep
          in: path
          description: The postal code that will be fetched from the API
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  schemas:
    ApiError:
      type: object
      properties:
        code:
          type: integer
          description: Error ID
          format: int32
        message:
          type: string
          description: Error Description
        description:
          type: string
          description: Error Details
      description: Error API responses
    Response:
      title: Response
      type: object
      properties:
        cep:
          title: Postal Code
          type: string
          description: Postal Code
          example: "09130200"
        state:
          title: State
          type: string
          description: State
          example: SP
        city:
          title: City
          type: string
          description: City
          example: Santo André
        street:
          title: Street
          type: string
          description: Street
          example: Rua Euclides de Figueiredo
        neighborhood:
          title: Neighborhood
          type: string
          description: Neighborhood
          example: Vila Lutécia
        location:
          $ref: '#/components/schemas/Location'
      description: Address response from API
    Location:
      title: Location
      type: object
      properties:
        type:
          title: Type
          type: string
          description: Location type
          example: Point
        coordinates:
          $ref: '#/components/schemas/Coordinates'
      description: Location object
    Coordinates:
      title: Coordinates
      type: object
      properties:
        longitude:
          title: Longitude
          type: string
          description: Longitude geolocation
          example: -46.5046571
        latitude:
          title: Latitude
          type: string
          description: Latitude geolocation
          example: -23.6920031
      description: Coordinates object
  responses:
    200-ok:
      description: Successful Request
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Response'
    400-BadRequest:
      description: Bad request
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ApiError'
    404-NotFound:
      description: Not found
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ApiError'
    500-Exception:
      description: Internal Server Error
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ApiError'
  parameters:
    cep:
      name: cep
      in: path
      description: The postal code that will be fetched from the API
      required: true
      schema:
        type: string
