global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'actuator-integration'

    scrape_interval: 5s
    metrics_path: /api/actuator/prometheus

    static_configs:
      - targets:
          - 'cepsearch-api:8080'
          - 'cepsearch-api:8081'